result=read.csv("/home/poulami/Dropbox/Poulami-project/to-share/data/result.csv")
sink("summary.txt")
summary(result$NoOfCommenters)
summary(result$comments)
summary(result$approval)
summary(result$no_of_days)
summary(result$owners)
sink()
jpeg("boxplots/NoOfCommenters.jpeg")
boxplot(result$NoOfCommenters,col=(c("dark grey")),ylab=("No of commenters"))
dev.off()
jpeg("boxplots/comments.jpeg")
boxplot(result$comments,col=(c("dark grey")),ylab=("No of comments"))
dev.off()
jpeg("boxplots/approval.jpeg")
boxplot(result$approval,col=(c("dark grey")),ylab=("No of approvals"))
dev.off()
jpeg("boxplots/no-of_days.jpeg")
boxplot(result$no_of_days,col=(c("dark grey")),ylab=("No of days"))
dev.off()
jpeg("boxplots/owners.jpeg")
boxplot(result$owners,col=(c("dark grey")),ylab=("Reviews owned by an individual"))
dev.off()
jpeg("histograms/NoOfCommenters.jpeg")
hist(result$NoOfCommenters,col=(c("dark grey")),xlab=("No of commenters"))
dev.off()
jpeg("histograms/comments.jpeg")
hist(result$comments,col=(c("dark grey")),xlab=("No of comments"))
dev.off()
jpeg("histograms/approval.jpeg")
hist(result$approval,col=(c("dark grey")),xlab=("No of approvals"))
dev.off()
jpeg("histograms/no-of_days.jpeg")
hist(result$no_of_days,col=(c("dark grey")),xlab=("No of days"))
dev.off()
jpeg("histograms/owners.jpeg")
hist(result$owners,col=(c("dark grey")),xlab=("Reviews owned by an individual"))
dev.off()


